<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eu.fbk.dkm.springles.ruleset" nsURI="http://eu.fbk.dkm.springles.ruleset" nsPrefix="eu.fbk.dkm.springles.ruleset"/>
